### ISSUE TITLE
Symbols source

### ISSUE THREAD

**Issue by emoose** [MeganGrass/Resident-Evil-4-HD-PC-Video-Project#1]
Hi there, just came across your project and saw there's some great work here, hope we'll get to see it continued, would help HD project a lot to move away from that awful Sofdec1 encoding...

I was going through some of the source and noticed a few symbol names were different to what I'd found (eg. `lr_rate_1504`), I've been compiling an IDA database for PC by using symbols from a bunch of different builds (GC debug, PS2, RE4VR...), but sadly each of those have their own missing pieces in different places, if you know of any other sources besides those it'd probably help a lot to fill them!

If you're still interested in RE4 reversing at all I've been collecting some things at https://github.com/emoose/re4-research, you can find my current IDA databases in the issues section there too, have named quite a lot (~70%) of the PC exe so far (no Ghidra unfortunately, but can probably be converted without too much work).

We're still trying to make improvements to the game with [re4_tweaks](https://github.com/nipkownix/re4_tweaks) too but there's a few areas we're still stuck in (mostly modelling/graphics/animation related), if you'd like to help with it at all it'd be very much appreciated!

**Comment by MeganGrass** [comment]
Hello!

I was using a few debug builds of RE4/Bio4 to fill in the gaps for the PC version in Ghidra, mostly the GCN and PS2 betas. During my dedication to the project a year or so ago, I was supposed to get ahold of a debug Wii build, which I believe would help much more than the GCN and PS2 builds, but covid restrictions are still hindering the dumping process.

Excellent work with [re4_tweaks](https://github.com/nipkownix/re4_tweaks)! Really impressive stuff!!

I didn't map out the executable 100%, but I did make a bit of progress here 'n there
![Untitled](https://user-images.githubusercontent.com/22947949/155564130-1f17840a-cd84-4fec-93bb-9b39360aa50d.png)

Feel free to reach out to me on [Twitter](https://twitter.com/MeganPuddin) :)
